FROM mcr.microsoft.com/devcontainers/python:3.11
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y     tesseract-ocr poppler-utils && rm -rf /var/lib/apt/lists/*
WORKDIR /workspaces/superrepo
